logging:
  level:
    root: INFO
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always

server:
  port: 7070

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem